### your site title here

title: Arie Soeteman
description: Portfolio of Arie Soeteman; Machine Learning for Automated Reasoning
affiliation: University of Amsterdam

# baseurl: /personal_webpage #name of GitHub repository
url: "https://ariesoeteman.github.io/" #custom url to be used instead of GitHub repository
author: Arie Soeteman
email: #

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - shortProject.md
      - longerProjectTitle.md
      - redirect.md
      - project4.md
      - project5.md
      - project6.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md
  - vendor/bundle/
  - gemini_output/
  - _posts/
  - 
  # - vendor/bundle/ruby/3.0.0/gems/jekyll-3.10.0/lib/site_template
  # - vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/site_template

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
